[package]
name = "testetst"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.0", default-features = false }

[dependencies.leafwing-input-manager]
git = "https://github.com/Shute052/leafwing-input-manager"
rev = "2b069dd"
default-features = false
