[package]
name = "bevy_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"
bevy_ecs_tilemap = "0.11"
rand = "0.8"
seldom_map_nav = { path = "../../projects/seldom_map_nav", features = [ "state", "log" ] }
seldom_state = "0.7"
